spring.application.name=CharityApplication

server.port=8080

debug=true

logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Show SQL later (optional)
# logging.level.org.hibernate.SQL=DEBUG

# ===============================
# THYMELEAF CONFIG
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=true

spring.devtools.restart.exclude=static/**,templates/**
# ===============================
# SESSION CONFIG (OPTIONAL)
# ===============================
server.servlet.session.timeout=3m



# ================= ORACLE DB =================
spring.datasource.url=jdbc:oracle:thin:@//10.255.24.9:1521/ORCLPDB
spring.datasource.username=appuser
spring.datasource.password=App123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ================= DEBUG =================
logging.level.org.springframework.jdbc=DEBUG


# ================= For Mails =================

spring.mail.host=mail.hhash.co.in
spring.mail.port=587
spring.mail.username=admin@hhash.co.in
spring.mail.password=tk5)5EYa6c-4DA

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=mail.hhash.co.in

